"""Role constants and helper groups for RBAC."""

ADMIN_ROLES = {"ADMINISTRADOR", "SUPERADMIN"}
AGENTE_ROLES = {"AGENTE"}
CLIENTE_ROLES = {"CLIENTE"}

STAFF_ROLES = ADMIN_ROLES | AGENTE_ROLES
ALL_ROLES = STAFF_ROLES | CLIENTE_ROLES
